// Package gentest turns confirmed findings into a runnable Foundry test. Each
// generated test reproduces one ordering dependency: it deploys the contract
// twice, runs the reader by itself on one copy and runs the writer just before
// the reader on the other, then asserts the reader's result changed. A developer
// can drop the file into a Foundry project, run it to see the effect for
// themselves, and keep it as a regression check once the issue is fixed.
//
// The generated file depends only on Foundry's built-in cheatcode address, not on
// forge-std, so it compiles and runs in any Foundry project without extra setup.
package gentest

import (
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/Hijanhv/Sequent/internal/report"
)

// vmAddress is Foundry's well-known cheatcode contract address.
const vmAddress = "0x7109709ECfa91a80626fF3989D68f67F5b1DD12D"

// Kind selects what the generated tests assert.
type Kind int

const (
	// Proof asserts the ordering effect is present. These tests pass on the
	// current (vulnerable) contract and fail once a fix removes the effect, so
	// they demonstrate the finding and verify a fix.
	Proof Kind = iota
	// Guard asserts the ordering effect is absent. These tests fail on the
	// current contract and pass once the issue is fixed, so kept in the repo they
	// guard against the bug being reintroduced.
	Guard
)

func (k Kind) suffix() string {
	if k == Guard {
		return "SequentGuard"
	}
	return "SequentRepro"
}

func (k Kind) headerComment() string {
	if k == Guard {
		return `// Generated by Sequent. Each test asserts an ordering effect is GONE. On the
// current contract these FAIL, because the effect is still present; once you fix
// the ordering issue they pass. Keep them to guard against the bug returning. Do
// not edit by hand; regenerate with sequent.`
	}
	return `// Generated by Sequent. Each test reproduces an ordering dependency: it runs the
// reader alone and then after the writer, on two fresh deployments, and asserts
// the reader's result changed. These pass while the flaw exists and fail once a
// fix removes it. Do not edit by hand; regenerate with sequent.`
}

// Options configures generation.
//
// A Proof test is self-contained: it embeds CreationCode and needs no source, so
// it reproduces the exact analyzed contract even from bytecode alone.
//
// A Guard test instead deploys the live contract from source, via
// type(<ContractName>).creationCode imported from SourceImport, with
// ConstructorArgs appended. That is what makes it a real regression guard: when
// the source is fixed it recompiles and the guard passes, and if the bug is ever
// reintroduced the guard fails again.
type Options struct {
	ContractName    string // Solidity contract identifier
	Kind            Kind
	CreationCode    []byte // Proof: the creation bytecode to embed
	SourceImport    string // Guard: import path of the source, e.g. "src/Vault.sol"
	ConstructorArgs []byte // Guard: encoded constructor args appended to the source's creation code
}

// Generate returns the Solidity source of a Foundry test for every confirmed
// finding, and the number of tests written. It returns ("", 0) when no finding
// is confirmed, so the caller can skip writing an empty file.
func Generate(opts Options, findings []report.Finding) (string, int) {
	var confirmed []report.Finding
	for _, f := range findings {
		if f.Confirmed && len(f.WriterCall) > 0 && len(f.ReaderCall) > 0 {
			confirmed = append(confirmed, f)
		}
	}
	if len(confirmed) == 0 {
		return "", 0
	}

	testName := identifier(opts.ContractName) + opts.Kind.suffix()
	imports, deployExpr := deploySource(opts)

	var b strings.Builder
	fmt.Fprintf(&b, `%s
pragma solidity ^0.8.19;

%sinterface Vm {
    function startPrank(address) external;
    function stopPrank() external;
}

contract %s {
    Vm constant vm = Vm(%s);
    address constant CALLER = address(0xCAFE);

    function _deploy() internal returns (address addr) {
        bytes memory code = %s;
        assembly {
            addr := create(0, add(code, 0x20), mload(code))
        }
        require(addr != address(0), "sequent: deploy failed");
    }
`, opts.Kind.headerComment(), imports, testName, vmAddress, deployExpr)

	used := make(map[string]int)
	for _, f := range confirmed {
		fn := testFuncName(used, f, opts.Kind)
		writeTest(&b, fn, f, opts.Kind)
	}

	b.WriteString("}\n")
	return b.String(), len(confirmed)
}

// deploySource returns the import block and the Solidity expression that yields
// the creation code to deploy. Proof embeds the bytecode; Guard pulls it from the
// live source so a later fix is reflected.
func deploySource(opts Options) (imports, deployExpr string) {
	if opts.Kind == Guard {
		imports = fmt.Sprintf("import {%s} from \"%s\";\n\n", opts.ContractName, opts.SourceImport)
		if len(opts.ConstructorArgs) > 0 {
			deployExpr = fmt.Sprintf("abi.encodePacked(type(%s).creationCode, hex\"%s\")", opts.ContractName, hex.EncodeToString(opts.ConstructorArgs))
		} else {
			deployExpr = fmt.Sprintf("type(%s).creationCode", opts.ContractName)
		}
		return imports, deployExpr
	}
	return "", fmt.Sprintf("hex\"%s\"", hex.EncodeToString(opts.CreationCode))
}

func writeTest(b *strings.Builder, fn string, f report.Finding, kind Kind) {
	assertion := `require(
            okBefore != okAfter || keccak256(outBefore) != keccak256(outAfter),
            "sequent: reordering did not change the reader"
        );`
	if kind == Guard {
		assertion = `require(
            okBefore == okAfter && keccak256(outBefore) == keccak256(outAfter),
            "sequent: reordering still changes the reader (regression)"
        );`
	}

	fmt.Fprintf(b, `
    // %s before %s: %s
    function %s() public {
        address baseline = _deploy();
        address attacked = _deploy();

        vm.startPrank(CALLER);
        (bool okBefore, bytes memory outBefore) = baseline.call(hex"%s");
        (bool ranWriter, ) = attacked.call(hex"%s");
        ranWriter; // the writer may or may not revert; we only assert on the reader
        (bool okAfter, bytes memory outAfter) = attacked.call(hex"%s");
        vm.stopPrank();

        %s
    }
`,
		f.Writer, f.Reader, effectComment(f), fn,
		hex.EncodeToString(f.ReaderCall),
		hex.EncodeToString(f.WriterCall),
		hex.EncodeToString(f.ReaderCall),
		assertion,
	)
}

func effectComment(f report.Finding) string {
	switch f.Effect {
	case "revert-flip":
		return "reader flips between reverting and succeeding"
	case "value-change":
		if f.Delta != nil {
			return "reader value changes by " + f.Delta.String()
		}
		return "reader value changes"
	default:
		return "reader output changes"
	}
}

// testFuncName builds a unique, valid Solidity test function name for a finding.
// Guard tests get an _is_fixed suffix so proof and guard names never collide.
func testFuncName(used map[string]int, f report.Finding, kind Kind) string {
	base := "test_" + identifier(f.Writer) + "_before_" + identifier(f.Reader)
	if kind == Guard {
		base += "_is_fixed"
	}
	used[base]++
	if n := used[base]; n > 1 {
		return fmt.Sprintf("%s_%d", base, n)
	}
	return base
}

// identifier reduces an arbitrary string to characters valid in a Solidity
// identifier, collapsing every run of other characters to a single underscore.
func identifier(s string) string {
	var b strings.Builder
	lastUnderscore := false
	for _, r := range s {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			lastUnderscore = false
			continue
		}
		if !lastUnderscore {
			b.WriteByte('_')
			lastUnderscore = true
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "fn"
	}
	return out
}
