// Package gentest turns confirmed findings into a runnable Foundry test. Each
// generated test reproduces one ordering dependency: it deploys the contract
// twice, runs the reader by itself on one copy and runs the writer just before
// the reader on the other, then asserts the reader's result changed. A developer
// can drop the file into a Foundry project, run it to see the effect for
// themselves, and keep it as a regression check once the issue is fixed.
//
// The generated file depends only on Foundry's built-in cheatcode address, not on
// forge-std, so it compiles and runs in any Foundry project without extra setup.
package gentest

import (
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/Hijanhv/Sequent/internal/report"
)

// vmAddress is Foundry's well-known cheatcode contract address.
const vmAddress = "0x7109709ECfa91a80626fF3989D68f67F5b1DD12D"

// Generate returns the Solidity source of a Foundry test reproducing every
// confirmed finding, and the number of tests written. It returns ("", 0) when no
// finding is confirmed, so the caller can skip writing an empty file.
func Generate(contractName string, creationBytecode []byte, findings []report.Finding) (string, int) {
	var confirmed []report.Finding
	for _, f := range findings {
		if f.Confirmed && len(f.WriterCall) > 0 && len(f.ReaderCall) > 0 {
			confirmed = append(confirmed, f)
		}
	}
	if len(confirmed) == 0 {
		return "", 0
	}

	testName := identifier(contractName) + "SequentRepro"

	var b strings.Builder
	fmt.Fprintf(&b, `// SPDX-License-Identifier: MIT
// Generated by Sequent. Each test reproduces an ordering dependency: it runs the
// reader alone and then after the writer, on two fresh deployments, and asserts
// the reader's result changed. Do not edit by hand; regenerate with sequent.
pragma solidity ^0.8.19;

interface Vm {
    function startPrank(address) external;
    function stopPrank() external;
}

contract %s {
    Vm constant vm = Vm(%s);
    address constant CALLER = address(0xCAFE);
    bytes internal creationCode = hex"%s";

    function _deploy() internal returns (address addr) {
        bytes memory code = creationCode;
        assembly {
            addr := create(0, add(code, 0x20), mload(code))
        }
        require(addr != address(0), "sequent: deploy failed");
    }
`, testName, vmAddress, hex.EncodeToString(creationBytecode))

	used := make(map[string]int)
	for _, f := range confirmed {
		fn := testFuncName(used, f)
		writeTest(&b, fn, f)
	}

	b.WriteString("}\n")
	return b.String(), len(confirmed)
}

func writeTest(b *strings.Builder, fn string, f report.Finding) {
	fmt.Fprintf(b, `
    // %s before %s: %s
    function %s() public {
        address baseline = _deploy();
        address attacked = _deploy();

        vm.startPrank(CALLER);
        (bool okBefore, bytes memory outBefore) = baseline.call(hex"%s");
        (bool ranWriter, ) = attacked.call(hex"%s");
        ranWriter; // the writer may or may not revert; we only assert the reader changed
        (bool okAfter, bytes memory outAfter) = attacked.call(hex"%s");
        vm.stopPrank();

        require(
            okBefore != okAfter || keccak256(outBefore) != keccak256(outAfter),
            "sequent: reordering did not change the reader"
        );
    }
`,
		f.Writer, f.Reader, effectComment(f), fn,
		hex.EncodeToString(f.ReaderCall),
		hex.EncodeToString(f.WriterCall),
		hex.EncodeToString(f.ReaderCall),
	)
}

func effectComment(f report.Finding) string {
	switch f.Effect {
	case "revert-flip":
		return "reader flips between reverting and succeeding"
	case "value-change":
		if f.Delta != nil {
			return "reader value changes by " + f.Delta.String()
		}
		return "reader value changes"
	default:
		return "reader output changes"
	}
}

// testFuncName builds a unique, valid Solidity test function name for a finding.
func testFuncName(used map[string]int, f report.Finding) string {
	base := "test_" + identifier(f.Writer) + "_before_" + identifier(f.Reader)
	used[base]++
	if n := used[base]; n > 1 {
		return fmt.Sprintf("%s_%d", base, n)
	}
	return base
}

// identifier reduces an arbitrary string to characters valid in a Solidity
// identifier, collapsing every run of other characters to a single underscore.
func identifier(s string) string {
	var b strings.Builder
	lastUnderscore := false
	for _, r := range s {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			lastUnderscore = false
			continue
		}
		if !lastUnderscore {
			b.WriteByte('_')
			lastUnderscore = true
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "fn"
	}
	return out
}
